name: Waka Time Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 * * *"
    
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          BRANCH: "main"
          COMMIT_MESSAGE: "Automated Coding Activity Update From Wakatime"
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
