name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "*/1 * * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: njammy/njammy@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: Updated the Readme
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
